### ISSUE TITLE
No me dejo crear cuenta, así que cree cuenta directamente en supabase

### ISSUE THREAD

**Issue by eliasbest07** [juliooa/the_agents#3]
Error: relation "public.profiles" does not exist
    at PrismaDb.getMessagesLimit (eval at instantiateModule (file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:17:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async POST (eval at instantiateModule (file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:14:23)
    at async Module.render_endpoint (eval at instantiateModule (file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:47:20)
    at async resolve (eval at instantiateModule (file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:375:17)        
    at async Module.respond (eval at instantiateModule (file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:248:20) 
    at async file:///C:/Users/Elias/Desktop/the_agents-main/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22

**Comment by eliasbest07** [comment]
Error mío >.<' lo resolví
